$change_sshd_config = <<-SCRIPT
echo 'change sshd_config to allow public key authentication & relaod sshd...'
sed -i 's/\#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/\#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/\#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $change_sshd_config
  config.vm.define "k8s-master-01" do |master_01|
    master_01.vm.box = "centos7"
    master_01.vm.hostname = "k8s-master-01"
    master_01.vm.provider "hyperv" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "k8s-node-01" do |node_01|
    node_01.vm.box = "centos7"
    node_01.vm.hostname = "k8s-node-01"
    node_01.vm.provider "hyperv" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "k8s-node-02" do |node_02|
    node_02.vm.box = "centos7"
    node_02.vm.hostname = "k8s-node-02"
    node_02.vm.provider "hyperv" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "k8s-docker-register" do |docker|
    docker.vm.box = "centos7"
    docker.vm.hostname = "k8s-docker-register"
    docker.vm.provider "hyperv" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
  config.vm.define "k8s-nfs" do |nfs|
    nfs.vm.box = "centos7"
    nfs.vm.hostname = "k8s-nfs"
    nfs.vm.provider "hyperv" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
end


Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "change_sshd_config.sh"
  config.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "file", source: "id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provider "hyperv" do |v|
      v.cpus = 2
      v.memory = 2048
  end
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.vm.define "master" do |master|
      master.vm.host_name = "master"
      #master.vm.network "private_network", ip: "192.168.137.200", auto_config: false
  end
  (1..2).each do |i|
      config.vm.define "node-#{i}" do |node|
          node.vm.host_name = "node#{i}"
          #node.vm.network "private_network", ip: "192.168.137.20#{i}", auto_config: false
      end
  end
end

